/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) uav_dynamics_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {18, 1, 1};

/* uav_dynamics_expl_vde_adj:(i0[12],i1[12],i2[6],i3[0])->(o0[18]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[0]? arg[0][6] : 0;
  a01=cos(a00);
  a02=arg[0]? arg[0][10] : 0;
  a03=arg[1]? arg[1][8] : 0;
  a04=(a02*a03);
  a05=arg[0]? arg[0][7] : 0;
  a06=cos(a05);
  a07=(a04/a06);
  a07=(a01*a07);
  a00=sin(a00);
  a08=arg[0]? arg[0][11] : 0;
  a09=(a08*a03);
  a10=(a09/a06);
  a10=(a00*a10);
  a07=(a07-a10);
  a10=arg[1]? arg[1][7] : 0;
  a11=(a08*a10);
  a11=(a01*a11);
  a07=(a07-a11);
  a11=(a02*a10);
  a11=(a00*a11);
  a07=(a07-a11);
  a11=tan(a05);
  a12=arg[1]? arg[1][6] : 0;
  a13=(a08*a12);
  a14=(a11*a13);
  a14=(a00*a14);
  a07=(a07-a14);
  a14=(a02*a12);
  a15=(a11*a14);
  a15=(a01*a15);
  a07=(a07+a15);
  a15=arg[2]? arg[2][2] : 0;
  a16=6.0240963855421692e-01;
  a17=arg[1]? arg[1][5] : 0;
  a17=(a16*a17);
  a18=(a15*a17);
  a19=(a06*a18);
  a19=(a00*a19);
  a07=(a07-a19);
  a19=arg[2]? arg[2][1] : 0;
  a20=(a19*a17);
  a21=(a06*a20);
  a21=(a01*a21);
  a07=(a07+a21);
  a21=arg[0]? arg[0][8] : 0;
  a22=cos(a21);
  a23=arg[1]? arg[1][4] : 0;
  a23=(a16*a23);
  a24=(a15*a23);
  a25=(a22*a24);
  a25=(a01*a25);
  a07=(a07-a25);
  a21=sin(a21);
  a05=sin(a05);
  a25=(a21*a05);
  a26=(a25*a24);
  a26=(a00*a26);
  a07=(a07-a26);
  a26=(a19*a23);
  a27=(a22*a26);
  a27=(a00*a27);
  a07=(a07-a27);
  a27=(a25*a26);
  a27=(a01*a27);
  a07=(a07+a27);
  a27=arg[1]? arg[1][3] : 0;
  a16=(a16*a27);
  a15=(a15*a16);
  a27=(a21*a15);
  a27=(a01*a27);
  a07=(a07+a27);
  a27=(a22*a05);
  a28=(a27*a15);
  a28=(a00*a28);
  a07=(a07-a28);
  a19=(a19*a16);
  a28=(a21*a19);
  a28=(a00*a28);
  a07=(a07+a28);
  a28=(a27*a19);
  a28=(a01*a28);
  a07=(a07+a28);
  if (res[0]!=0) res[0][6]=a07;
  a07=(a01/a06);
  a28=(a07/a06);
  a28=(a28*a09);
  a28=(a05*a28);
  a09=(a00/a06);
  a29=(a09/a06);
  a29=(a29*a04);
  a29=(a05*a29);
  a28=(a28+a29);
  a13=(a01*a13);
  a29=casadi_sq(a06);
  a13=(a13/a29);
  a28=(a28+a13);
  a14=(a00*a14);
  a14=(a14/a29);
  a28=(a28+a14);
  a18=(a01*a18);
  a18=(a05*a18);
  a28=(a28-a18);
  a18=arg[2]? arg[2][0] : 0;
  a14=(a18*a17);
  a14=(a06*a14);
  a28=(a28-a14);
  a20=(a00*a20);
  a20=(a05*a20);
  a28=(a28-a20);
  a20=(a01*a24);
  a14=(a21*a20);
  a14=(a06*a14);
  a28=(a28+a14);
  a14=(a00*a26);
  a29=(a21*a14);
  a29=(a06*a29);
  a28=(a28+a29);
  a29=(a18*a23);
  a13=(a21*a29);
  a13=(a05*a13);
  a28=(a28-a13);
  a13=(a01*a15);
  a04=(a22*a13);
  a04=(a06*a04);
  a28=(a28+a04);
  a04=(a00*a19);
  a30=(a22*a04);
  a30=(a06*a30);
  a28=(a28+a30);
  a18=(a18*a16);
  a30=(a22*a18);
  a30=(a05*a30);
  a28=(a28-a30);
  if (res[0]!=0) res[0][7]=a28;
  a24=(a00*a24);
  a24=(a21*a24);
  a20=(a05*a20);
  a20=(a22*a20);
  a24=(a24+a20);
  a26=(a01*a26);
  a26=(a21*a26);
  a24=(a24-a26);
  a14=(a05*a14);
  a14=(a22*a14);
  a24=(a24+a14);
  a29=(a06*a29);
  a29=(a22*a29);
  a24=(a24+a29);
  a15=(a00*a15);
  a15=(a22*a15);
  a24=(a24+a15);
  a13=(a05*a13);
  a13=(a21*a13);
  a24=(a24-a13);
  a19=(a01*a19);
  a19=(a22*a19);
  a24=(a24-a19);
  a04=(a05*a04);
  a04=(a21*a04);
  a24=(a24-a04);
  a18=(a06*a18);
  a18=(a21*a18);
  a24=(a24-a18);
  if (res[0]!=0) res[0][8]=a24;
  a24=8.0000000000000002e-02;
  a18=(a24*a08);
  a04=20.;
  a19=arg[1]? arg[1][10] : 0;
  a19=(a04*a19);
  a13=(a18*a19);
  a15=5.0000000000000003e-02;
  a29=(a15*a02);
  a14=1.2500000000000000e+01;
  a26=arg[1]? arg[1][11] : 0;
  a14=(a14*a26);
  a26=(a29*a14);
  a13=(a13-a26);
  a26=(a02*a14);
  a20=(a08*a19);
  a26=(a26-a20);
  a26=(a15*a26);
  a13=(a13+a26);
  a13=(a13+a12);
  if (res[0]!=0) res[0][9]=a13;
  a13=arg[0]? arg[0][9] : 0;
  a26=(a15*a13);
  a20=(a26*a14);
  a28=arg[1]? arg[1][9] : 0;
  a04=(a04*a28);
  a08=(a08*a04);
  a28=(a13*a14);
  a08=(a08-a28);
  a15=(a15*a08);
  a20=(a20+a15);
  a18=(a18*a04);
  a20=(a20-a18);
  a09=(a09*a03);
  a20=(a20+a09);
  a09=(a01*a10);
  a20=(a20+a09);
  a09=(a00*a11);
  a09=(a09*a12);
  a20=(a20+a09);
  if (res[0]!=0) res[0][10]=a20;
  a29=(a29*a04);
  a26=(a26*a19);
  a29=(a29-a26);
  a13=(a13*a19);
  a02=(a02*a04);
  a13=(a13-a02);
  a24=(a24*a13);
  a29=(a29+a24);
  a07=(a07*a03);
  a29=(a29+a07);
  a10=(a00*a10);
  a29=(a29-a10);
  a11=(a01*a11);
  a11=(a11*a12);
  a29=(a29+a11);
  if (res[0]!=0) res[0][11]=a29;
  a29=(a21*a06);
  a29=(a29*a23);
  a05=(a05*a17);
  a29=(a29-a05);
  a05=(a22*a06);
  a05=(a05*a16);
  a29=(a29+a05);
  if (res[0]!=0) res[0][12]=a29;
  a29=(a06*a00);
  a29=(a29*a17);
  a05=(a25*a00);
  a11=(a22*a01);
  a05=(a05+a11);
  a05=(a05*a23);
  a29=(a29+a05);
  a05=(a27*a00);
  a11=(a21*a01);
  a05=(a05-a11);
  a05=(a05*a16);
  a29=(a29+a05);
  if (res[0]!=0) res[0][13]=a29;
  a06=(a06*a01);
  a06=(a06*a17);
  a25=(a25*a01);
  a22=(a22*a00);
  a25=(a25-a22);
  a25=(a25*a23);
  a06=(a06+a25);
  a27=(a27*a01);
  a21=(a21*a00);
  a27=(a27+a21);
  a27=(a27*a16);
  a06=(a06+a27);
  if (res[0]!=0) res[0][14]=a06;
  if (res[0]!=0) res[0][15]=a04;
  if (res[0]!=0) res[0][16]=a19;
  if (res[0]!=0) res[0][17]=a14;
  return 0;
}

CASADI_SYMBOL_EXPORT int uav_dynamics_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int uav_dynamics_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int uav_dynamics_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void uav_dynamics_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int uav_dynamics_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void uav_dynamics_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void uav_dynamics_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void uav_dynamics_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int uav_dynamics_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int uav_dynamics_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real uav_dynamics_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* uav_dynamics_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* uav_dynamics_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* uav_dynamics_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* uav_dynamics_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int uav_dynamics_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int uav_dynamics_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
